server {
    listen 80;
    
    # 1. Definición para el health check
    # La igualdad (=) hace que sea una coincidencia exacta y muy rápida
    location = /health.html {
        root   /usr/share/nginx/html;
        access_log off; # Opcional: evita llenar logs con los pings del ALB
    }

    # 2. Configuración principal de la SPA
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Redirige cualquier petición de ruta hacia el index.html
        try_files $uri $uri/ /index.html; 
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}